# The SQL SELECT DISTINCT Statement

In [1]:
import pandasql
from pandasql import sqldf
import pandas as pd

In [2]:
from warnings import filterwarnings
filterwarnings("ignore")

In [3]:
A = pd.read_csv("C:/Users/I A T Laptop L.L.C/Desktop/JupyterN/Credit.csv")
A

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
396,397,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
397,398,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
398,399,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0
399,400,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

The SELECT DISTINCT statement is used to return only distinct (different) values.

Inside a table, a column often contains many duplicate values; and sometimes you only want to list the different (distinct) values.

SELECT DISTINCT column1, column2, ...
FROM table_name;

In [4]:
sqldf("select * from A")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
396,397,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
397,398,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
398,399,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0
399,400,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

In [5]:
sqldf("select Education from A") # All columns

     Education
0           11
1           15
2           11
3           11
4           16
..         ...
395         13
396         17
397         12
398         13
399          7

[400 rows x 1 columns]

# find distinct values of Education column

In [6]:
sqldf("select distinct Education from A") # showing only dictinct results

    Education
0          11
1          15
2          16
3          10
4          12
5           9
6          13
7          19
8          14
9           7
10         17
11          8
12          5
13         20
14         18
15          6

# find count of distinct values of Education column

In [7]:
sqldf("select COUNT(DISTINCT Education) FROM A")

   COUNT(DISTINCT Education)
0                         16

# *** WHERE clause***

SELECT column1, column2, ...
FROM table_name
WHERE condition;

***The WHERE clause is not only used in SELECT statements, it is also used in UPDATE, DELETE, etc.!***

# Solved Examples on where clause

# select all columns from table where Ethnicity is Asian

In [8]:
sqldf("select * from A where Ethnicity='Asian'")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,2,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
1,3,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
2,4,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
3,8,8,71.408,7114,512,2,87,9,Male,No,No,Asian,872
4,13,13,80.616,5308,394,1,57,7,Female,No,Yes,Asian,204
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,386,386,26.400,5640,398,3,58,15,Female,No,No,Asian,905
98,388,388,16.529,1357,126,3,62,9,Male,No,No,Asian,0
99,391,391,135.118,10578,747,3,81,15,Female,No,Yes,Asian,1393
100,393,393,25.974,2308,196,2,24,10,Male,No,No,Asian,0
101,400,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

# select data from table where Age is greater than 50

In [9]:
sqldf("select * from A where Age > 50")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,2,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
1,3,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
2,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
3,6,6,80.180,8047,569,4,77,10,Male,No,No,Caucasian,1151
4,8,8,71.408,7114,512,2,87,9,Male,No,No,Asian,872
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,391,391,135.118,10578,747,3,81,15,Female,No,Yes,Asian,1393
223,394,394,17.316,1335,138,2,65,13,Male,No,No,African American,0
224,397,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
225,398,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
226,400,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

# select all columns from table where Ethnicity is not Asian

# ** NOT**

In [10]:
sqldf("select * from A where not Ethnicity ='Asian'")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
2,6,6,80.180,8047,569,4,77,10,Male,No,No,Caucasian,1151
3,7,7,20.996,3388,259,2,37,12,Female,No,No,African American,203
4,9,9,15.125,3300,266,5,66,13,Female,No,No,Caucasian,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,395,395,49.794,5758,410,4,40,8,Male,No,No,Caucasian,734
294,396,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
295,397,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
296,398,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
297,399,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0

# Select all records where the Cards column has the value 5.

In [11]:
sqldf("select * from A where Cards = 5")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,9,9,15.125,3300,266,5,66,13,Female,No,No,Caucasian,279
1,24,24,64.027,5179,398,5,48,8,Male,No,Yes,African American,411
2,26,26,14.090,4323,326,5,25,16,Female,No,Yes,African American,671
3,32,32,28.941,2733,210,5,43,16,Male,No,Yes,Asian,0
4,96,96,14.084,855,120,5,46,17,Female,No,Yes,African American,0
5,100,100,83.851,8494,607,5,47,18,Male,No,No,Caucasian,1311
6,110,110,13.561,3261,279,5,37,19,Male,No,Yes,Asian,297
7,116,116,40.442,4828,369,5,81,8,Female,No,No,African American,510
8,127,127,26.427,5533,433,5,50,15,Female,Yes,Yes,Asian,1404
9,132,132,10.726,1568,162,5,46,19,Male,No,Yes,Asian,0
10,150,150,13.444,886,121,5,44,10,Male,No,Yes,Asian,0
11,157,157,31.811,4284,338,5,75,13,Female,No,Yes,Caucasian,429
12,161,161,12.238,4865,381,5,67,11,Female,No,No,Caucasian,836
13,164,164,13.676,2330,203,5,80,16,Female,No,No,African American,0
14,180,180,58.026,7499,560,5,67,11,Female,No,No,Caucasian,1237
15,181,181,10.635,3584,294,5,69,16,Male,No,Yes,Asian,423
16,204,204,68.206,6784,499,5,40,16,Female,Yes,No,African American,1411
17,208,208,10.842,4391,358,5,37,10,Female,Yes,Yes,Caucasian,1216
18,222,222,98.515,8760,633,5,78,11,Female,No,No,African American,1230
19,224,224,27.512,4613,344,5,72,17,Male,No,Yes,Asian,573
20,238,238,60.579,5149,388,5,38,15,Male,No,Yes,Asian,443
21,241,241,29.705,3351,262,5,71,14,Female,No,Yes,Asian,148
22,246,246,34.509,2001,189,5,80,18,Female,No,Yes,African American,0
23,252,252,28.474,3202,267,5,66,12,Male,No,Yes,Caucasian,132
24,275,275,30.550,5869,439,5,81,9,Female,No,No,African American,967
25,291,291,26.370,3235,268,5,78,11,Male,No,Yes,Asian,159
26,296,296,27.272,1389,149,5,67,10,Female,No,Yes,Caucasian,0
27,320,320,27.590,2586,229,5,54,16,Male,No,Yes,African American,0
28,343,343,14.595,2955,260,5,37,9,Male,No,Yes,African American,204
29,347,347,21.551,5380,420,5,51,18,Male,No,Yes,Asian,907
30,376,376,20.974,5673,413,5,44,16,Female,No,Yes,Caucasian,1000
31,397,397,13.364,3838,296,5,65,17,Male,No,No,African American,480
32,398,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
33,400,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

# Select all records where the Ethnicity column has the value 'Asian' and the Education column has the value 10.

In [12]:
sqldf("select * from A where Ethnicity ='Asian' AND Education = 10")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,54,54,16.304,5466,413,4,66,10,Male,No,Yes,Asian,957
1,150,150,13.444,886,121,5,44,10,Male,No,Yes,Asian,0
2,219,219,10.627,1647,149,2,71,10,Female,Yes,Yes,Asian,195
3,345,345,48.218,5199,401,7,39,10,Male,No,Yes,Asian,633
4,393,393,25.974,2308,196,2,24,10,Male,No,No,Asian,0

# Select all records where the Ethnicity column has the value 'Asian' or Caucasian

In [13]:
sqldf("select * from A where Ethnicity ='Asian' or Ethnicity ='Caucasian'")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,2,2,106.025,6645,483,3,82,15,Female,Yes,Yes,Asian,903
2,3,3,104.593,7075,514,4,71,11,Male,No,No,Asian,580
3,4,4,148.924,9504,681,3,36,11,Female,No,No,Asian,964
4,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,395,395,49.794,5758,410,4,40,8,Male,No,No,Caucasian,734
297,396,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
298,398,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
299,399,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0
300,400,400,18.701,5524,415,5,64,7,Female,No,No,Asian,966

# **** ORDER BY*****

The ORDER BY keyword is used to sort the result-set in ascending or descending order.

The ORDER BY keyword sorts the records in ascending order by default. To sort the records in descending order, use the DESC keyword.

# Syntax
SELECT column1, column2, ...
FROM table_name
ORDER BY column1, column2, ... ASC|DESC;

In [14]:
sqldf("select * from A order by Ethnicity")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,7,7,20.996,3388,259,2,37,12,Female,No,No,African American,203
1,10,10,71.061,6819,491,3,41,19,Female,Yes,Yes,African American,1350
2,15,15,19.144,3291,269,2,75,13,Female,No,No,African American,148
3,16,16,20.089,2525,200,3,57,15,Female,No,Yes,African American,0
4,17,17,53.598,3714,286,3,73,17,Female,No,Yes,African American,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,392,392,73.327,6555,472,2,43,15,Female,No,No,Caucasian,721
396,395,395,49.794,5758,410,4,40,8,Male,No,No,Caucasian,734
397,396,396,12.096,4100,307,3,32,13,Male,No,Yes,Caucasian,560
398,398,398,57.872,4171,321,5,67,12,Female,No,Yes,Caucasian,138
399,399,399,37.728,2525,192,1,44,13,Male,No,Yes,Caucasian,0

In [15]:
sqldf("select * from A order by Ethnicity desc")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
2,6,6,80.180,8047,569,4,77,10,Male,No,No,Caucasian,1151
3,9,9,15.125,3300,266,5,66,13,Female,No,No,Caucasian,279
4,11,11,63.095,8117,589,4,30,14,Male,No,Yes,Caucasian,1407
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,381,381,115.123,7760,538,3,83,14,Female,No,No,African American,661
396,385,385,20.088,1870,180,3,76,16,Male,No,No,African American,0
397,387,387,19.253,3683,287,4,57,10,Male,No,No,African American,371
398,394,394,17.316,1335,138,2,65,13,Male,No,No,African American,0
399,397,397,13.364,3838,296,5,65,17,Male,No,No,African American,480

In [16]:
sqldf("select * from A order by Education,Income")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,31,31,34.142,5666,413,4,47,5,Female,No,Yes,Caucasian,863
1,285,285,14.711,2047,167,2,67,6,Male,No,Yes,Caucasian,0
2,309,309,14.956,4640,332,2,33,6,Male,No,No,Asian,681
3,255,255,36.508,6386,469,4,79,6,Female,No,Yes,Caucasian,1048
4,369,369,89.000,5759,440,3,37,6,Female,No,No,Caucasian,345
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,216,216,41.025,4229,337,3,79,19,Female,No,Yes,Caucasian,246
396,10,10,71.061,6819,491,3,41,19,Female,Yes,Yes,African American,1350
397,194,194,130.209,10088,730,7,39,19,Female,No,Yes,Caucasian,1426
398,61,61,35.510,5198,364,2,35,20,Female,No,No,Asian,631
399,52,52,39.705,3969,301,2,27,20,Male,No,Yes,African American,211

In [17]:
sqldf("select *  from A order by Education,Income")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,31,31,34.142,5666,413,4,47,5,Female,No,Yes,Caucasian,863
1,285,285,14.711,2047,167,2,67,6,Male,No,Yes,Caucasian,0
2,309,309,14.956,4640,332,2,33,6,Male,No,No,Asian,681
3,255,255,36.508,6386,469,4,79,6,Female,No,Yes,Caucasian,1048
4,369,369,89.000,5759,440,3,37,6,Female,No,No,Caucasian,345
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,216,216,41.025,4229,337,3,79,19,Female,No,Yes,Caucasian,246
396,10,10,71.061,6819,491,3,41,19,Female,Yes,Yes,African American,1350
397,194,194,130.209,10088,730,7,39,19,Female,No,Yes,Caucasian,1426
398,61,61,35.510,5198,364,2,35,20,Female,No,No,Asian,631
399,52,52,39.705,3969,301,2,27,20,Male,No,Yes,African American,211

In [18]:
sqldf("select Education,Income from A order by Education,Income")

     Education   Income
0            5   34.142
1            6   14.711
2            6   14.956
3            6   36.508
4            6   89.000
..         ...      ...
395         19   41.025
396         19   71.061
397         19  130.209
398         20   35.510
399         20   39.705

[400 rows x 2 columns]

In [19]:
sqldf("SELECT * FROM A ORDER BY Ethnicity ASC, Education ASC")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,140,140,107.841,10384,728,3,87,7,Male,No,No,African American,1597
1,24,24,64.027,5179,398,5,48,8,Male,No,Yes,African American,411
2,89,89,15.560,4307,352,4,57,8,Male,No,Yes,African American,579
3,116,116,40.442,4828,369,5,81,8,Female,No,No,African American,510
4,137,137,54.663,4116,314,2,70,8,Female,No,No,African American,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,194,194,130.209,10088,730,7,39,19,Female,No,Yes,Caucasian,1426
396,216,216,41.025,4229,337,3,79,19,Female,No,Yes,Caucasian,246
397,239,239,26.532,2910,236,6,58,19,Female,No,Yes,Caucasian,52
398,248,248,36.364,2220,188,3,50,19,Male,No,No,Caucasian,0
399,379,379,19.349,4941,366,1,33,19,Male,No,Yes,Caucasian,717

# EXERCISE on Order by

# Select all records from the table, sort the result reversed alphabetically by the column Ethnicity.

In [20]:
sqldf("select * from A order by Ethnicity desc")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,1,1,14.891,3606,283,2,34,11,Male,No,Yes,Caucasian,333
1,5,5,55.882,4897,357,2,68,16,Male,No,Yes,Caucasian,331
2,6,6,80.180,8047,569,4,77,10,Male,No,No,Caucasian,1151
3,9,9,15.125,3300,266,5,66,13,Female,No,No,Caucasian,279
4,11,11,63.095,8117,589,4,30,14,Male,No,Yes,Caucasian,1407
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,381,381,115.123,7760,538,3,83,14,Female,No,No,African American,661
396,385,385,20.088,1870,180,3,76,16,Male,No,No,African American,0
397,387,387,19.253,3683,287,4,57,10,Male,No,No,African American,371
398,394,394,17.316,1335,138,2,65,13,Male,No,No,African American,0
399,397,397,13.364,3838,296,5,65,17,Male,No,No,African American,480

# Select all records from the  table, sort the result alphabetically, first by the column Ethnicity, then, by the column Age.

In [21]:
sqldf("select * from A order by Ethnicity, Age")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,26,26,14.090,4323,326,5,25,16,Female,No,Yes,African American,671
1,236,236,10.503,2923,232,3,25,18,Female,No,Yes,African American,191
2,94,94,16.479,5435,388,2,26,16,Male,No,No,African American,937
3,52,52,39.705,3969,301,2,27,20,Male,No,Yes,African American,211
4,76,76,33.017,3180,224,2,28,16,Male,No,Yes,African American,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,380,380,53.308,2860,214,1,84,10,Male,No,Yes,Caucasian,0
396,382,382,101.788,8029,574,2,84,11,Male,No,Yes,Caucasian,849
397,190,190,58.351,4411,326,2,85,16,Female,No,Yes,Caucasian,126
398,267,267,88.830,4952,360,4,86,16,Female,No,Yes,Caucasian,15
399,324,324,182.728,13913,982,4,98,17,Male,No,Yes,Caucasian,1999

# Select all records from the table, sort the result Numericaly by the Age.

In [22]:
sqldf("select * from A order by Age asc")

,Unnamed: 0,ID,Income,Limit,Rating,Cards,Age,Education,Gender,Student,Married,Ethnicity,Balance
0,336,336,24.314,3409,270,2,23,7,Female,No,Yes,Caucasian,194
1,44,44,36.929,6257,445,1,24,14,Female,No,Yes,Asian,976
2,153,153,41.419,2120,184,4,24,11,Female,Yes,No,Caucasian,156
3,393,393,25.974,2308,196,2,24,10,Male,No,No,Asian,0
4,26,26,14.090,4323,326,5,25,16,Female,No,Yes,African American,671
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,8,8,71.408,7114,512,2,87,9,Male,No,No,Asian,872
396,140,140,107.841,10384,728,3,87,7,Male,No,No,African American,1597
397,129,129,123.299,8376,610,2,89,17,Male,Yes,No,African American,1259
398,210,210,151.947,9156,642,2,91,11,Female,No,Yes,African American,732
399,324,324,182.728,13913,982,4,98,17,Male,No,Yes,Caucasian,1999

# The SQL INSERT INTO Statement

# The SQL INSERT INTO Statement
The INSERT INTO statement is used to insert new records in a table.

INSERT INTO Syntax
It is possible to write the INSERT INTO statement in two ways:

1. Specify both the column names and the values to be inserted:

INSERT INTO table_name (column1, column2, column3, ...)
VALUES (value1, value2, value3, ...);

2. If you are adding values for all the columns of the table, you do not need to specify the column names in the SQL query. However, make sure the order of the values is in the same order as the columns in the table. Here, the INSERT INTO syntax would be as follows:

INSERT INTO table_name
VALUES (value1, value2, value3, ...);

In [33]:
import csv, sqlite3

con = sqlite3.connect("my_db1.db")
cur = con.cursor()

In [34]:
%sql sqlite:///my_db1.db

In [36]:
import pandas as pd
df = pd.read_csv("C:/Users/I A T Laptop L.L.C/Desktop/JupyterN/Credit.csv")
df.to_sql("cred", con, if_exists='replace', index=False,method="multi")

In [37]:
%sql select * from cred

 * sqlite:///my_db1.db
   sqlite:///new_schema.db
Done.

[(1, 1, 14.891, 3606, 283, 2, 34, 11, ' Male', 'No', 'Yes', 'Caucasian', 333),
 (2, 2, 106.025, 6645, 483, 3, 82, 15, 'Female', 'Yes', 'Yes', 'Asian', 903),
 (3, 3, 104.593, 7075, 514, 4, 71, 11, ' Male', 'No', 'No', 'Asian', 580),
 (4, 4, 148.924, 9504, 681, 3, 36, 11, 'Female', 'No', 'No', 'Asian', 964),
 (5, 5, 55.882, 4897, 357, 2, 68, 16, ' Male', 'No', 'Yes', 'Caucasian', 331),
 (6, 6, 80.18, 8047, 569, 4, 77, 10, ' Male', 'No', 'No', 'Caucasian', 1151),
 (7, 7, 20.996, 3388, 259, 2, 37, 12, 'Female', 'No', 'No', 'African American', 203),
 (8, 8, 71.408, 7114, 512, 2, 87, 9, ' Male', 'No', 'No', 'Asian', 872),
 (9, 9, 15.125, 3300, 266, 5, 66, 13, 'Female', 'No', 'No', 'Caucasian', 279),
 (10, 10, 71.061, 6819, 491, 3, 41, 19, 'Female', 'Yes', 'Yes', 'African American', 1350),
 (11, 11, 63.095, 8117, 589, 4, 30, 14, ' Male', 'No', 'Yes', 'Caucasian', 1407),
 (12, 12, 15.045, 1311, 138, 3, 64, 16, ' Male', 'No', 'No', 'Caucasian', 0),
 (13, 13, 80.616, 5308, 394, 1, 57, 7, 'Female', 'No', 'Yes', 'Asian', 204),
 (14, 14, 43.682, 6922, 511, 1, 49, 9, ' Male', 'No', 'Yes', 'Caucasian', 1081),
 (15, 15, 19.144, 3291, 269, 2, 75, 13, 'Female', 'No', 'No', 'African American', 148),
 (16, 16, 20.089, 2525, 200, 3, 57, 15, 'Female', 'No', 'Yes', 'African American', 0),
 (17, 17, 53.598, 3714, 286, 3, 73, 17, 'Female', 'No', 'Yes', 'African American', 0),
 (18, 18, 36.496, 4378, 339, 3, 69, 15, 'Female', 'No', 'Yes', 'Asian', 368),
 (19, 19, 49.57, 6384, 448, 1, 28, 9, 'Female', 'No', 'Yes', 'Asian', 891),
 (20, 20, 42.079, 6626, 479, 2, 44, 9, ' Male', 'No', 'No', 'Asian', 1048),
 (21, 21, 17.7, 2860, 235, 4, 63, 16, 'Female', 'No', 'No', 'Asian', 89),
 (22, 22, 37.348, 6378, 458, 1, 72, 17, 'Female', 'No', 'No', 'Caucasian', 968),
 (23, 23, 20.103, 2631, 213, 3, 61, 10, ' Male', 'No', 'Yes', 'African American', 0),
 (24, 24, 64.027, 5179, 398, 5, 48, 8, ' Male', 'No', 'Yes', 'African American', 411),
 (25, 25, 10.742, 1757, 156, 3, 57, 15, 'Female', 'No', 'No', 'Caucasian', 0),
 (26, 26, 14.09, 4323, 326, 5, 25, 16, 'Female', 'No', 'Yes', 'African American', 671),
 (27, 27, 42.471, 3625, 289, 6, 44, 12, 'Female', 'Yes', 'No', 'Caucasian', 654),
 (28, 28, 32.793, 4534, 333, 2, 44, 16, ' Male', 'No', 'No', 'African American', 467),
 (29, 29, 186.634, 13414, 949, 2, 41, 14, 'Female', 'No', 'Yes', 'African American', 1809),
 (30, 30, 26.813, 5611, 411, 4, 55, 16, 'Female', 'No', 'No', 'Caucasian', 915),
 (31, 31, 34.142, 5666, 413, 4, 47, 5, 'Female', 'No', 'Yes', 'Caucasian', 863),
 (32, 32, 28.941, 2733, 210, 5, 43, 16, ' Male', 'No', 'Yes', 'Asian', 0),
 (33, 33, 134.181, 7838, 563, 2, 48, 13, 'Female', 'No', 'No', 'Caucasian', 526),
 (34, 34, 31.367, 1829, 162, 4, 30, 10, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (35, 35, 20.15, 2646, 199, 2, 25, 14, 'Female', 'No', 'Yes', 'Asian', 0),
 (36, 36, 23.35, 2558, 220, 3, 49, 12, 'Female', 'Yes', 'No', 'Caucasian', 419),
 (37, 37, 62.413, 6457, 455, 2, 71, 11, 'Female', 'No', 'Yes', 'Caucasian', 762),
 (38, 38, 30.007, 6481, 462, 2, 69, 9, 'Female', 'No', 'Yes', 'Caucasian', 1093),
 (39, 39, 11.795, 3899, 300, 4, 25, 10, 'Female', 'No', 'No', 'Caucasian', 531),
 (40, 40, 13.647, 3461, 264, 4, 47, 14, ' Male', 'No', 'Yes', 'Caucasian', 344),
 (41, 41, 34.95, 3327, 253, 3, 54, 14, 'Female', 'No', 'No', 'African American', 50),
 (42, 42, 113.659, 7659, 538, 2, 66, 15, ' Male', 'Yes', 'Yes', 'African American', 1155),
 (43, 43, 44.158, 4763, 351, 2, 66, 13, 'Female', 'No', 'Yes', 'Asian', 385),
 (44, 44, 36.929, 6257, 445, 1, 24, 14, 'Female', 'No', 'Yes', 'Asian', 976),
 (45, 45, 31.861, 6375, 469, 3, 25, 16, 'Female', 'No', 'Yes', 'Caucasian', 1120),
 (46, 46, 77.38, 7569, 564, 3, 50, 12, 'Female', 'No', 'Yes', 'Caucasian', 997),
 (47, 47, 19.531, 5043, 376, 2, 64, 16, 'Female', 'Yes', 'Yes', 'Asian', 1241),
 (48, 48, 44.646, 4431, 320, 2, 49, 15, ' Male', 'Yes', 'Yes', 'Caucasian', 797),
 (49, 49, 44.522, 2252, 205, 6, 72, 15, ' Male', 'No', 'Yes', 'Asian', 0),
 (50, 50, 43.479, 4569, 354, 4, 49, 13, ' Male', 'Yes', 'Yes', 'African American', 902),
 (51, 51, 36.362, 5183, 376, 3, 49, 15, ' Male', 'No', 'Yes', 'African American', 654),
 (52, 52, 39.705, 3969, 301, 2, 27, 20, ' Male', 'No', 'Yes', 'African American', 211),
 (53, 53, 44.205, 5441, 394, 1, 32, 12, ' Male', 'No', 'Yes', 'Caucasian', 607),
 (54, 54, 16.304, 5466, 413, 4, 66, 10, ' Male', 'No', 'Yes', 'Asian', 957),
 (55, 55, 15.333, 1499, 138, 2, 47, 9, 'Female', 'No', 'Yes', 'Asian', 0),
 (56, 56, 32.916, 1786, 154, 2, 60, 8, 'Female', 'No', 'Yes', 'Asian', 0),
 (57, 57, 57.1, 4742, 372, 7, 79, 18, 'Female', 'No', 'Yes', 'Asian', 379),
 (58, 58, 76.273, 4779, 367, 4, 65, 14, 'Female', 'No', 'Yes', 'Caucasian', 133),
 (59, 59, 10.354, 3480, 281, 2, 70, 17, ' Male', 'No', 'Yes', 'Caucasian', 333),
 (60, 60, 51.872, 5294, 390, 4, 81, 17, 'Female', 'No', 'No', 'Caucasian', 531),
 (61, 61, 35.51, 5198, 364, 2, 35, 20, 'Female', 'No', 'No', 'Asian', 631),
 (62, 62, 21.238, 3089, 254, 3, 59, 10, 'Female', 'No', 'No', 'Caucasian', 108),
 (63, 63, 30.682, 1671, 160, 2, 77, 7, 'Female', 'No', 'No', 'Caucasian', 0),
 (64, 64, 14.132, 2998, 251, 4, 75, 17, ' Male', 'No', 'No', 'Caucasian', 133),
 (65, 65, 32.164, 2937, 223, 2, 79, 15, 'Female', 'No', 'Yes', 'African American', 0),
 (66, 66, 12.0, 4160, 320, 4, 28, 14, 'Female', 'No', 'Yes', 'Caucasian', 602),
 (67, 67, 113.829, 9704, 694, 4, 38, 13, 'Female', 'No', 'Yes', 'Asian', 1388),
 (68, 68, 11.187, 5099, 380, 4, 69, 16, 'Female', 'No', 'No', 'African American', 889),
 (69, 69, 27.847, 5619, 418, 2, 78, 15, 'Female', 'No', 'Yes', 'Caucasian', 822),
 (70, 70, 49.502, 6819, 505, 4, 55, 14, ' Male', 'No', 'Yes', 'Caucasian', 1084),
 (71, 71, 24.889, 3954, 318, 4, 75, 12, ' Male', 'No', 'Yes', 'Caucasian', 357),
 (72, 72, 58.781, 7402, 538, 2, 81, 12, 'Female', 'No', 'Yes', 'Asian', 1103),
 (73, 73, 22.939, 4923, 355, 1, 47, 18, 'Female', 'No', 'Yes', 'Asian', 663),
 (74, 74, 23.989, 4523, 338, 4, 31, 15, ' Male', 'No', 'No', 'Caucasian', 601),
 (75, 75, 16.103, 5390, 418, 4, 45, 10, 'Female', 'No', 'Yes', 'Caucasian', 945),
 (76, 76, 33.017, 3180, 224, 2, 28, 16, ' Male', 'No', 'Yes', 'African American', 29),
 (77, 77, 30.622, 3293, 251, 1, 68, 16, ' Male', 'Yes', 'No', 'Caucasian', 532),
 (78, 78, 20.936, 3254, 253, 1, 30, 15, 'Female', 'No', 'No', 'Asian', 145),
 (79, 79, 110.968, 6662, 468, 3, 45, 11, 'Female', 'No', 'Yes', 'Caucasian', 391),
 (80, 80, 15.354, 2101, 171, 2, 65, 14, ' Male', 'No', 'No', 'Asian', 0),
 (81, 81, 27.369, 3449, 288, 3, 40, 9, 'Female', 'No', 'Yes', 'Caucasian', 162),
 (82, 82, 53.48, 4263, 317, 1, 83, 15, ' Male', 'No', 'No', 'Caucasian', 99),
 (83, 83, 23.672, 4433, 344, 3, 63, 11, ' Male', 'No', 'No', 'Caucasian', 503),
 (84, 84, 19.225, 1433, 122, 3, 38, 14, 'Female', 'No', 'No', 'Caucasian', 0),
 (85, 85, 43.54, 2906, 232, 4, 69, 11, ' Male', 'No', 'No', 'Caucasian', 0),
 (86, 86, 152.298, 12066, 828, 4, 41, 12, 'Female', 'No', 'Yes', 'Asian', 1779),
 (87, 87, 55.367, 6340, 448, 1, 33, 15, ' Male', 'No', 'Yes', 'Caucasian', 815),
 (88, 88, 11.741, 2271, 182, 4, 59, 12, 'Female', 'No', 'No', 'Asian', 0),
 (89, 89, 15.56, 4307, 352, 4, 57, 8, ' Male', 'No', 'Yes', 'African American', 579),
 (90, 90, 59.53, 7518, 543, 3, 52, 9, 'Female', 'No', 'No', 'African American', 1176),
 (91, 91, 20.191, 5767, 431, 4, 42, 16, ' Male', 'No', 'Yes', 'African American', 1023),
 (92, 92, 48.498, 6040, 456, 3, 47, 16, ' Male', 'No', 'Yes', 'Caucasian', 812),
 (93, 93, 30.733, 2832, 249, 4, 51, 13, ' Male', 'No', 'No', 'Caucasian', 0),
 (94, 94, 16.479, 5435, 388, 2, 26, 16, ' Male', 'No', 'No', 'African American', 937),
 (95, 95, 38.009, 3075, 245, 3, 45, 15, 'Female', 'No', 'No', 'African American', 0),
 (96, 96, 14.084, 855, 120, 5, 46, 17, 'Female', 'No', 'Yes', 'African American', 0),
 (97, 97, 14.312, 5382, 367, 1, 59, 17, ' Male', 'Yes', 'No', 'Asian', 1380),
 (98, 98, 26.067, 3388, 266, 4, 74, 17, 'Female', 'No', 'Yes', 'African American', 155),
 (99, 99, 36.295, 2963, 241, 2, 68, 14, 'Female', 'Yes', 'No', 'African American', 375),
 (100, 100, 83.851, 8494, 607, 5, 47, 18, ' Male', 'No', 'No', 'Caucasian', 1311),
 (101, 101, 21.153, 3736, 256, 1, 41, 11, ' Male', 'No', 'No', 'Caucasian', 298),
 (102, 102, 17.976, 2433, 190, 3, 70, 16, 'Female', 'Yes', 'No', 'Caucasian', 431),
 (103, 103, 68.713, 7582, 531, 2, 56, 16, ' Male', 'Yes', 'No', 'Caucasian', 1587),
 (104, 104, 146.183, 9540, 682, 6, 66, 15, ' Male', 'No', 'No', 'Caucasian', 1050),
 (105, 105, 15.846, 4768, 365, 4, 53, 12, 'Female', 'No', 'No', 'Caucasian', 745),
 (106, 106, 12.031, 3182, 259, 2, 58, 18, 'Female', 'No', 'Yes', 'Caucasian', 210),
 (107, 107, 16.819, 1337, 115, 2, 74, 15, ' Male', 'No', 'Yes', 'Asian', 0),
 (108, 108, 39.11, 3189, 263, 3, 72, 12, ' Male', 'No', 'No', 'Asian', 0),
 (109, 109, 107.986, 6033, 449, 4, 64, 14, ' Male', 'No', 'Yes', 'Caucasian', 227),
 (110, 110, 13.561, 3261, 279, 5, 37, 19, ' Male', 'No', 'Yes', 'Asian', 297),
 (111, 111, 34.537, 3271, 250, 3, 57, 17, 'Female', 'No', 'Yes', 'Asian', 47),
 (112, 112, 28.575, 2959, 231, 2, 60, 11, 'Female', 'No', 'No', 'African American', 0),
 (113, 113, 46.007, 6637, 491, 4, 42, 14, ' Male', 'No', 'Yes', 'Caucasian', 1046),
 (114, 114, 69.251, 6386, 474, 4, 30, 12, 'Female', 'No', 'Yes', 'Asian', 768),
 (115, 115, 16.482, 3326, 268, 4, 41, 15, ' Male', 'No', 'No', 'Caucasian', 271),
 (116, 116, 40.442, 4828, 369, 5, 81, 8, 'Female', 'No', 'No', 'African American', 510),
 (117, 117, 35.177, 2117, 186, 3, 62, 16, 'Female', 'No', 'No', 'Caucasian', 0),
 (118, 118, 91.362, 9113, 626, 1, 47, 17, ' Male', 'No', 'Yes', 'Asian', 1341),
 (119, 119, 27.039, 2161, 173, 3, 40, 17, 'Female', 'No', 'No', 'Caucasian', 0),
 (120, 120, 23.012, 1410, 137, 3, 81, 16, ' Male', 'No', 'No', 'Caucasian', 0),
 (121, 121, 27.241, 1402, 128, 2, 67, 15, 'Female', 'No', 'Yes', 'Asian', 0),
 (122, 122, 148.08, 8157, 599, 2, 83, 13, ' Male', 'No', 'Yes', 'Caucasian', 454),
 (123, 123, 62.602, 7056, 481, 1, 84, 11, 'Female', 'No', 'No', 'Caucasian', 904),
 (124, 124, 11.808, 1300, 117, 3, 77, 14, 'Female', 'No', 'No', 'African American', 0),
 (125, 125, 29.564, 2529, 192, 1, 30, 12, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (126, 126, 27.578, 2531, 195, 1, 34, 15, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (127, 127, 26.427, 5533, 433, 5, 50, 15, 'Female', 'Yes', 'Yes', 'Asian', 1404),
 (128, 128, 57.202, 3411, 259, 3, 72, 11, 'Female', 'No', 'No', 'Caucasian', 0),
 (129, 129, 123.299, 8376, 610, 2, 89, 17, ' Male', 'Yes', 'No', 'African American', 1259),
 (130, 130, 18.145, 3461, 279, 3, 56, 15, ' Male', 'No', 'Yes', 'African American', 255),
 (131, 131, 23.793, 3821, 281, 4, 56, 12, 'Female', 'Yes', 'Yes', 'African American', 868),
 (132, 132, 10.726, 1568, 162, 5, 46, 19, ' Male', 'No', 'Yes', 'Asian', 0),
 (133, 133, 23.283, 5443, 407, 4, 49, 13, ' Male', 'No', 'Yes', 'African American', 912),
 (134, 134, 21.455, 5829, 427, 4, 80, 12, 'Female', 'No', 'Yes', 'African American', 1018),
 (135, 135, 34.664, 5835, 452, 3, 77, 15, 'Female', 'No', 'Yes', 'African American', 835),
 (136, 136, 44.473, 3500, 257, 3, 81, 16, 'Female', 'No', 'No', 'African American', 8),
 (137, 137, 54.663, 4116, 314, 2, 70, 8, 'Female', 'No', 'No', 'African American', 75),
 (138, 138, 36.355, 3613, 278, 4, 35, 9, ' Male', 'No', 'Yes', 'Asian', 187),
 (139, 139, 21.374, 2073, 175, 2, 74, 11, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (140, 140, 107.841, 10384, 728, 3, 87, 7, ' Male', 'No', 'No', 'African American', 1597),
 (141, 141, 39.831, 6045, 459, 3, 32, 12, 'Female', 'Yes', 'Yes', 'African American', 1425),
 (142, 142, 91.876, 6754, 483, 2, 33, 10, ' Male', 'No', 'Yes', 'Caucasian', 605),
 (143, 143, 103.893, 7416, 549, 3, 84, 17, ' Male', 'No', 'No', 'Asian', 669),
 (144, 144, 19.636, 4896, 387, 3, 64, 10, 'Female', 'No', 'No', 'African American', 710),
 (145, 145, 17.392, 2748, 228, 3, 32, 14, ' Male', 'No', 'Yes', 'Caucasian', 68),
 (146, 146, 19.529, 4673, 341, 2, 51, 14, ' Male', 'No', 'No', 'Asian', 642),
 (147, 147, 17.055, 5110, 371, 3, 55, 15, 'Female', 'No', 'Yes', 'Caucasian', 805),
 (148, 148, 23.857, 1501, 150, 3, 56, 16, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (149, 149, 15.184, 2420, 192, 2, 69, 11, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (150, 150, 13.444, 886, 121, 5, 44, 10, ' Male', 'No', 'Yes', 'Asian', 0),
 (151, 151, 63.931, 5728, 435, 3, 28, 14, 'Female', 'No', 'Yes', 'African American', 581),
 (152, 152, 35.864, 4831, 353, 3, 66, 13, 'Female', 'No', 'Yes', 'Caucasian', 534),
 (153, 153, 41.419, 2120, 184, 4, 24, 11, 'Female', 'Yes', 'No', 'Caucasian', 156),
 (154, 154, 92.112, 4612, 344, 3, 32, 17, ' Male', 'No', 'No', 'Caucasian', 0),
 (155, 155, 55.056, 3155, 235, 2, 31, 16, ' Male', 'No', 'Yes', 'African American', 0),
 (156, 156, 19.537, 1362, 143, 4, 34, 9, 'Female', 'No', 'Yes', 'Asian', 0),
 (157, 157, 31.811, 4284, 338, 5, 75, 13, 'Female', 'No', 'Yes', 'Caucasian', 429),
 (158, 158, 56.256, 5521, 406, 2, 72, 16, 'Female', 'Yes', 'Yes', 'Caucasian', 1020),
 (159, 159, 42.357, 5550, 406, 2, 83, 12, 'Female', 'No', 'Yes', 'Asian', 653),
 (160, 160, 53.319, 3000, 235, 3, 53, 13, ' Male', 'No', 'No', 'Asian', 0),
 (161, 161, 12.238, 4865, 381, 5, 67, 11, 'Female', 'No', 'No', 'Caucasian', 836),
 (162, 162, 31.353, 1705, 160, 3, 81, 14, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (163, 163, 63.809, 7530, 515, 1, 56, 12, ' Male', 'No', 'Yes', 'Caucasian', 1086),
 (164, 164, 13.676, 2330, 203, 5, 80, 16, 'Female', 'No', 'No', 'African American', 0),
 (165, 165, 76.782, 5977, 429, 4, 44, 12, ' Male', 'No', 'Yes', 'Asian', 548),
 (166, 166, 25.383, 4527, 367, 4, 46, 11, ' Male', 'No', 'Yes', 'Caucasian', 570),
 (167, 167, 35.691, 2880, 214, 2, 35, 15, ' Male', 'No', 'No', 'African American', 0),
 (168, 168, 29.403, 2327, 178, 1, 37, 14, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (169, 169, 27.47, 2820, 219, 1, 32, 11, 'Female', 'No', 'Yes', 'Asian', 0),
 (170, 170, 27.33, 6179, 459, 4, 36, 12, 'Female', 'No', 'Yes', 'Caucasian', 1099),
 (171, 171, 34.772, 2021, 167, 3, 57, 9, ' Male', 'No', 'No', 'Asian', 0),
 (172, 172, 36.934, 4270, 299, 1, 63, 9, 'Female', 'No', 'Yes', 'Caucasian', 283),
 (173, 173, 76.348, 4697, 344, 4, 60, 18, ' Male', 'No', 'No', 'Asian', 108),
 (174, 174, 14.887, 4745, 339, 3, 58, 12, ' Male', 'No', 'Yes', 'African American', 724),
 (175, 175, 121.834, 10673, 750, 3, 54, 16, ' Male', 'No', 'No', 'African American', 1573),
 (176, 176, 30.132, 2168, 206, 3, 52, 17, ' Male', 'No', 'No', 'Caucasian', 0),
 (177, 177, 24.05, 2607, 221, 4, 32, 18, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (178, 178, 22.379, 3965, 292, 2, 34, 14, 'Female', 'No', 'Yes', 'Asian', 384),
 (179, 179, 28.316, 4391, 316, 2, 29, 10, 'Female', 'No', 'No', 'Caucasian', 453),
 (180, 180, 58.026, 7499, 560, 5, 67, 11, 'Female', 'No', 'No', 'Caucasian', 1237),
 (181, 181, 10.635, 3584, 294, 5, 69, 16, ' Male', 'No', 'Yes', 'Asian', 423),
 (182, 182, 46.102, 5180, 382, 3, 81, 12, ' Male', 'No', 'Yes', 'African American', 516),
 (183, 183, 58.929, 6420, 459, 2, 66, 9, 'Female', 'No', 'Yes', 'African American', 789),
 (184, 184, 80.861, 4090, 335, 3, 29, 15, 'Female', 'No', 'Yes', 'Asian', 0),
 (185, 185, 158.889, 11589, 805, 1, 62, 17, 'Female', 'No', 'Yes', 'Caucasian', 1448),
 (186, 186, 30.42, 4442, 316, 1, 30, 14, 'Female', 'No', 'No', 'African American', 450),
 (187, 187, 36.472, 3806, 309, 2, 52, 13, ' Male', 'No', 'No', 'African American', 188),
 (188, 188, 23.365, 2179, 167, 2, 75, 15, ' Male', 'No', 'No', 'Asian', 0),
 (189, 189, 83.869, 7667, 554, 2, 83, 11, ' Male', 'No', 'No', 'African American', 930),
 (190, 190, 58.351, 4411, 326, 2, 85, 16, 'Female', 'No', 'Yes', 'Caucasian', 126),
 (191, 191, 55.187, 5352, 385, 4, 50, 17, 'Female', 'No', 'Yes', 'Caucasian', 538),
 (192, 192, 124.29, 9560, 701, 3, 52, 17, 'Female', 'Yes', 'No', 'Asian', 1687),
 (193, 193, 28.508, 3933, 287, 4, 56, 14, ' Male', 'No', 'Yes', 'Asian', 336),
 (194, 194, 130.209, 10088, 730, 7, 39, 19, 'Female', 'No', 'Yes', 'Caucasian', 1426),
 (195, 195, 30.406, 2120, 181, 2, 79, 14, ' Male', 'No', 'Yes', 'African American', 0),
 (196, 196, 23.883, 5384, 398, 2, 73, 16, 'Female', 'No', 'Yes', 'African American', 802),
 (197, 197, 93.039, 7398, 517, 1, 67, 12, ' Male', 'No', 'Yes', 'African American', 749),
 (198, 198, 50.699, 3977, 304, 2, 84, 17, 'Female', 'No', 'No', 'African American', 69),
 (199, 199, 27.349, 2000, 169, 4, 51, 16, 'Female', 'No', 'Yes', 'African American', 0),
 (200, 200, 10.403, 4159, 310, 3, 43, 7, ' Male', 'No', 'Yes', 'Asian', 571),
 (201, 201, 23.949, 5343, 383, 2, 40, 18, ' Male', 'No', 'Yes', 'African American', 829),
 (202, 202, 73.914, 7333, 529, 6, 67, 15, 'Female', 'No', 'Yes', 'Caucasian', 1048),
 (203, 203, 21.038, 1448, 145, 2, 58, 13, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (204, 204, 68.206, 6784, 499, 5, 40, 16, 'Female', 'Yes', 'No', 'African American', 1411),
 (205, 205, 57.337, 5310, 392, 2, 45, 7, 'Female', 'No', 'No', 'Caucasian', 456),
 (206, 206, 10.793, 3878, 321, 8, 29, 13, ' Male', 'No', 'No', 'Caucasian', 638),
 (207, 207, 23.45, 2450, 180, 2, 78, 13, ' Male', 'No', 'No', 'Caucasian', 0),
 (208, 208, 10.842, 4391, 358, 5, 37, 10, 'Female', 'Yes', 'Yes', 'Caucasian', 1216),
 (209, 209, 51.345, 4327, 320, 3, 46, 15, ' Male', 'No', 'No', 'African American', 230),
 (210, 210, 151.947, 9156, 642, 2, 91, 11, 'Female', 'No', 'Yes', 'African American', 732),
 (211, 211, 24.543, 3206, 243, 2, 62, 12, 'Female', 'No', 'Yes', 'Caucasian', 95),
 (212, 212, 29.567, 5309, 397, 3, 25, 15, ' Male', 'No', 'No', 'Caucasian', 799),
 (213, 213, 39.145, 4351, 323, 2, 66, 13, ' Male', 'No', 'Yes', 'Caucasian', 308),
 (214, 214, 39.422, 5245, 383, 2, 44, 19, ' Male', 'No', 'No', 'African American', 637),
 (215, 215, 34.909, 5289, 410, 2, 62, 16, 'Female', 'No', 'Yes', 'Caucasian', 681),
 (216, 216, 41.025, 4229, 337, 3, 79, 19, 'Female', 'No', 'Yes', 'Caucasian', 246),
 (217, 217, 15.476, 2762, 215, 3, 60, 18, ' Male', 'No', 'No', 'Asian', 52),
 (218, 218, 12.456, 5395, 392, 3, 65, 14, ' Male', 'No', 'Yes', 'Caucasian', 955),
 (219, 219, 10.627, 1647, 149, 2, 71, 10, 'Female', 'Yes', 'Yes', 'Asian', 195),
 (220, 220, 38.954, 5222, 370, 4, 76, 13, 'Female', 'No', 'No', 'Caucasian', 653),
 (221, 221, 44.847, 5765, 437, 3, 53, 13, 'Female', 'Yes', 'No', 'Asian', 1246),
 (222, 222, 98.515, 8760, 633, 5, 78, 11, 'Female', 'No', 'No', 'African American', 1230),
 (223, 223, 33.437, 6207, 451, 4, 44, 9, ' Male', 'Yes', 'No', 'Caucasian', 1549),
 (224, 224, 27.512, 4613, 344, 5, 72, 17, ' Male', 'No', 'Yes', 'Asian', 573),
 (225, 225, 121.709, 7818, 584, 4, 50, 6, ' Male', 'No', 'Yes', 'Caucasian', 701),
 (226, 226, 15.079, 5673, 411, 4, 28, 15, 'Female', 'No', 'Yes', 'Asian', 1075),
 (227, 227, 59.879, 6906, 527, 6, 78, 15, 'Female', 'No', 'No', 'Caucasian', 1032),
 (228, 228, 66.989, 5614, 430, 3, 47, 14, 'Female', 'No', 'Yes', 'Caucasian', 482),
 (229, 229, 69.165, 4668, 341, 2, 34, 11, 'Female', 'No', 'No', 'African American', 156),
 (230, 230, 69.943, 7555, 547, 3, 76, 9, ' Male', 'No', 'Yes', 'Asian', 1058),
 (231, 231, 33.214, 5137, 387, 3, 59, 9, ' Male', 'No', 'No', 'African American', 661),
 (232, 232, 25.124, 4776, 378, 4, 29, 12, ' Male', 'No', 'Yes', 'Caucasian', 657),
 (233, 233, 15.741, 4788, 360, 1, 39, 14, ' Male', 'No', 'Yes', 'Asian', 689),
 (234, 234, 11.603, 2278, 187, 3, 71, 11, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (235, 235, 69.656, 8244, 579, 3, 41, 14, ' Male', 'No', 'Yes', 'African American', 1329),
 (236, 236, 10.503, 2923, 232, 3, 25, 18, 'Female', 'No', 'Yes', 'African American', 191),
 (237, 237, 42.529, 4986, 369, 2, 37, 11, ' Male', 'No', 'Yes', 'Asian', 489),
 (238, 238, 60.579, 5149, 388, 5, 38, 15, ' Male', 'No', 'Yes', 'Asian', 443),
 (239, 239, 26.532, 2910, 236, 6, 58, 19, 'Female', 'No', 'Yes', 'Caucasian', 52),
 (240, 240, 27.952, 3557, 263, 1, 35, 13, 'Female', 'No', 'Yes', 'Asian', 163),
 (241, 241, 29.705, 3351, 262, 5, 71, 14, 'Female', 'No', 'Yes', 'Asian', 148),

In [43]:
%sql INSERT INTO cred values ('140','140','107.841','10384','728','3','87','7','Male','No','No','African American','1597')

 * sqlite:///my_db1.db
   sqlite:///new_schema.db
1 rows affected.

[]

In [51]:
%sql select * from cred

 * sqlite:///my_db1.db
   sqlite:///new_schema.db
Done.

[(1, 1, 14.891, 3606, 283, 2, 34, 11, ' Male', 'No', 'Yes', 'Caucasian', 333),
 (2, 2, 106.025, 6645, 483, 3, 82, 15, 'Female', 'Yes', 'Yes', 'Asian', 903),
 (3, 3, 104.593, 7075, 514, 4, 71, 11, ' Male', 'No', 'No', 'Asian', 580),
 (4, 4, 148.924, 9504, 681, 3, 36, 11, 'Female', 'No', 'No', 'Asian', 964),
 (5, 5, 55.882, 4897, 357, 2, 68, 16, ' Male', 'No', 'Yes', 'Caucasian', 331),
 (6, 6, 80.18, 8047, 569, 4, 77, 10, ' Male', 'No', 'No', 'Caucasian', 1151),
 (7, 7, 20.996, 3388, 259, 2, 37, 12, 'Female', 'No', 'No', 'African American', 203),
 (8, 8, 71.408, 7114, 512, 2, 87, 9, ' Male', 'No', 'No', 'Asian', 872),
 (9, 9, 15.125, 3300, 266, 5, 66, 13, 'Female', 'No', 'No', 'Caucasian', 279),
 (10, 10, 71.061, 6819, 491, 3, 41, 19, 'Female', 'Yes', 'Yes', 'African American', 1350),
 (11, 11, 63.095, 8117, 589, 4, 30, 14, ' Male', 'No', 'Yes', 'Caucasian', 1407),
 (12, 12, 15.045, 1311, 138, 3, 64, 16, ' Male', 'No', 'No', 'Caucasian', 0),
 (13, 13, 80.616, 5308, 394, 1, 57, 7, 'Female', 'No', 'Yes', 'Asian', 204),
 (14, 14, 43.682, 6922, 511, 1, 49, 9, ' Male', 'No', 'Yes', 'Caucasian', 1081),
 (15, 15, 19.144, 3291, 269, 2, 75, 13, 'Female', 'No', 'No', 'African American', 148),
 (16, 16, 20.089, 2525, 200, 3, 57, 15, 'Female', 'No', 'Yes', 'African American', 0),
 (17, 17, 53.598, 3714, 286, 3, 73, 17, 'Female', 'No', 'Yes', 'African American', 0),
 (18, 18, 36.496, 4378, 339, 3, 69, 15, 'Female', 'No', 'Yes', 'Asian', 368),
 (19, 19, 49.57, 6384, 448, 1, 28, 9, 'Female', 'No', 'Yes', 'Asian', 891),
 (20, 20, 42.079, 6626, 479, 2, 44, 9, ' Male', 'No', 'No', 'Asian', 1048),
 (21, 21, 17.7, 2860, 235, 4, 63, 16, 'Female', 'No', 'No', 'Asian', 89),
 (22, 22, 37.348, 6378, 458, 1, 72, 17, 'Female', 'No', 'No', 'Caucasian', 968),
 (23, 23, 20.103, 2631, 213, 3, 61, 10, ' Male', 'No', 'Yes', 'African American', 0),
 (24, 24, 64.027, 5179, 398, 5, 48, 8, ' Male', 'No', 'Yes', 'African American', 411),
 (25, 25, 10.742, 1757, 156, 3, 57, 15, 'Female', 'No', 'No', 'Caucasian', 0),
 (26, 26, 14.09, 4323, 326, 5, 25, 16, 'Female', 'No', 'Yes', 'African American', 671),
 (27, 27, 42.471, 3625, 289, 6, 44, 12, 'Female', 'Yes', 'No', 'Caucasian', 654),
 (28, 28, 32.793, 4534, 333, 2, 44, 16, ' Male', 'No', 'No', 'African American', 467),
 (29, 29, 186.634, 13414, 949, 2, 41, 14, 'Female', 'No', 'Yes', 'African American', 1809),
 (30, 30, 26.813, 5611, 411, 4, 55, 16, 'Female', 'No', 'No', 'Caucasian', 915),
 (31, 31, 34.142, 5666, 413, 4, 47, 5, 'Female', 'No', 'Yes', 'Caucasian', 863),
 (32, 32, 28.941, 2733, 210, 5, 43, 16, ' Male', 'No', 'Yes', 'Asian', 0),
 (33, 33, 134.181, 7838, 563, 2, 48, 13, 'Female', 'No', 'No', 'Caucasian', 526),
 (34, 34, 31.367, 1829, 162, 4, 30, 10, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (35, 35, 20.15, 2646, 199, 2, 25, 14, 'Female', 'No', 'Yes', 'Asian', 0),
 (36, 36, 23.35, 2558, 220, 3, 49, 12, 'Female', 'Yes', 'No', 'Caucasian', 419),
 (37, 37, 62.413, 6457, 455, 2, 71, 11, 'Female', 'No', 'Yes', 'Caucasian', 762),
 (38, 38, 30.007, 6481, 462, 2, 69, 9, 'Female', 'No', 'Yes', 'Caucasian', 1093),
 (39, 39, 11.795, 3899, 300, 4, 25, 10, 'Female', 'No', 'No', 'Caucasian', 531),
 (40, 40, 13.647, 3461, 264, 4, 47, 14, ' Male', 'No', 'Yes', 'Caucasian', 344),
 (41, 41, 34.95, 3327, 253, 3, 54, 14, 'Female', 'No', 'No', 'African American', 50),
 (42, 42, 113.659, 7659, 538, 2, 66, 15, ' Male', 'Yes', 'Yes', 'African American', 1155),
 (43, 43, 44.158, 4763, 351, 2, 66, 13, 'Female', 'No', 'Yes', 'Asian', 385),
 (44, 44, 36.929, 6257, 445, 1, 24, 14, 'Female', 'No', 'Yes', 'Asian', 976),
 (45, 45, 31.861, 6375, 469, 3, 25, 16, 'Female', 'No', 'Yes', 'Caucasian', 1120),
 (46, 46, 77.38, 7569, 564, 3, 50, 12, 'Female', 'No', 'Yes', 'Caucasian', 997),
 (47, 47, 19.531, 5043, 376, 2, 64, 16, 'Female', 'Yes', 'Yes', 'Asian', 1241),
 (48, 48, 44.646, 4431, 320, 2, 49, 15, ' Male', 'Yes', 'Yes', 'Caucasian', 797),
 (49, 49, 44.522, 2252, 205, 6, 72, 15, ' Male', 'No', 'Yes', 'Asian', 0),
 (50, 50, 43.479, 4569, 354, 4, 49, 13, ' Male', 'Yes', 'Yes', 'African American', 902),
 (51, 51, 36.362, 5183, 376, 3, 49, 15, ' Male', 'No', 'Yes', 'African American', 654),
 (52, 52, 39.705, 3969, 301, 2, 27, 20, ' Male', 'No', 'Yes', 'African American', 211),
 (53, 53, 44.205, 5441, 394, 1, 32, 12, ' Male', 'No', 'Yes', 'Caucasian', 607),
 (54, 54, 16.304, 5466, 413, 4, 66, 10, ' Male', 'No', 'Yes', 'Asian', 957),
 (55, 55, 15.333, 1499, 138, 2, 47, 9, 'Female', 'No', 'Yes', 'Asian', 0),
 (56, 56, 32.916, 1786, 154, 2, 60, 8, 'Female', 'No', 'Yes', 'Asian', 0),
 (57, 57, 57.1, 4742, 372, 7, 79, 18, 'Female', 'No', 'Yes', 'Asian', 379),
 (58, 58, 76.273, 4779, 367, 4, 65, 14, 'Female', 'No', 'Yes', 'Caucasian', 133),
 (59, 59, 10.354, 3480, 281, 2, 70, 17, ' Male', 'No', 'Yes', 'Caucasian', 333),
 (60, 60, 51.872, 5294, 390, 4, 81, 17, 'Female', 'No', 'No', 'Caucasian', 531),
 (61, 61, 35.51, 5198, 364, 2, 35, 20, 'Female', 'No', 'No', 'Asian', 631),
 (62, 62, 21.238, 3089, 254, 3, 59, 10, 'Female', 'No', 'No', 'Caucasian', 108),
 (63, 63, 30.682, 1671, 160, 2, 77, 7, 'Female', 'No', 'No', 'Caucasian', 0),
 (64, 64, 14.132, 2998, 251, 4, 75, 17, ' Male', 'No', 'No', 'Caucasian', 133),
 (65, 65, 32.164, 2937, 223, 2, 79, 15, 'Female', 'No', 'Yes', 'African American', 0),
 (66, 66, 12.0, 4160, 320, 4, 28, 14, 'Female', 'No', 'Yes', 'Caucasian', 602),
 (67, 67, 113.829, 9704, 694, 4, 38, 13, 'Female', 'No', 'Yes', 'Asian', 1388),
 (68, 68, 11.187, 5099, 380, 4, 69, 16, 'Female', 'No', 'No', 'African American', 889),
 (69, 69, 27.847, 5619, 418, 2, 78, 15, 'Female', 'No', 'Yes', 'Caucasian', 822),
 (70, 70, 49.502, 6819, 505, 4, 55, 14, ' Male', 'No', 'Yes', 'Caucasian', 1084),
 (71, 71, 24.889, 3954, 318, 4, 75, 12, ' Male', 'No', 'Yes', 'Caucasian', 357),
 (72, 72, 58.781, 7402, 538, 2, 81, 12, 'Female', 'No', 'Yes', 'Asian', 1103),
 (73, 73, 22.939, 4923, 355, 1, 47, 18, 'Female', 'No', 'Yes', 'Asian', 663),
 (74, 74, 23.989, 4523, 338, 4, 31, 15, ' Male', 'No', 'No', 'Caucasian', 601),
 (75, 75, 16.103, 5390, 418, 4, 45, 10, 'Female', 'No', 'Yes', 'Caucasian', 945),
 (76, 76, 33.017, 3180, 224, 2, 28, 16, ' Male', 'No', 'Yes', 'African American', 29),
 (77, 77, 30.622, 3293, 251, 1, 68, 16, ' Male', 'Yes', 'No', 'Caucasian', 532),
 (78, 78, 20.936, 3254, 253, 1, 30, 15, 'Female', 'No', 'No', 'Asian', 145),
 (79, 79, 110.968, 6662, 468, 3, 45, 11, 'Female', 'No', 'Yes', 'Caucasian', 391),
 (80, 80, 15.354, 2101, 171, 2, 65, 14, ' Male', 'No', 'No', 'Asian', 0),
 (81, 81, 27.369, 3449, 288, 3, 40, 9, 'Female', 'No', 'Yes', 'Caucasian', 162),
 (82, 82, 53.48, 4263, 317, 1, 83, 15, ' Male', 'No', 'No', 'Caucasian', 99),
 (83, 83, 23.672, 4433, 344, 3, 63, 11, ' Male', 'No', 'No', 'Caucasian', 503),
 (84, 84, 19.225, 1433, 122, 3, 38, 14, 'Female', 'No', 'No', 'Caucasian', 0),
 (85, 85, 43.54, 2906, 232, 4, 69, 11, ' Male', 'No', 'No', 'Caucasian', 0),
 (86, 86, 152.298, 12066, 828, 4, 41, 12, 'Female', 'No', 'Yes', 'Asian', 1779),
 (87, 87, 55.367, 6340, 448, 1, 33, 15, ' Male', 'No', 'Yes', 'Caucasian', 815),
 (88, 88, 11.741, 2271, 182, 4, 59, 12, 'Female', 'No', 'No', 'Asian', 0),
 (89, 89, 15.56, 4307, 352, 4, 57, 8, ' Male', 'No', 'Yes', 'African American', 579),
 (90, 90, 59.53, 7518, 543, 3, 52, 9, 'Female', 'No', 'No', 'African American', 1176),
 (91, 91, 20.191, 5767, 431, 4, 42, 16, ' Male', 'No', 'Yes', 'African American', 1023),
 (92, 92, 48.498, 6040, 456, 3, 47, 16, ' Male', 'No', 'Yes', 'Caucasian', 812),
 (93, 93, 30.733, 2832, 249, 4, 51, 13, ' Male', 'No', 'No', 'Caucasian', 0),
 (94, 94, 16.479, 5435, 388, 2, 26, 16, ' Male', 'No', 'No', 'African American', 937),
 (95, 95, 38.009, 3075, 245, 3, 45, 15, 'Female', 'No', 'No', 'African American', 0),
 (96, 96, 14.084, 855, 120, 5, 46, 17, 'Female', 'No', 'Yes', 'African American', 0),
 (97, 97, 14.312, 5382, 367, 1, 59, 17, ' Male', 'Yes', 'No', 'Asian', 1380),
 (98, 98, 26.067, 3388, 266, 4, 74, 17, 'Female', 'No', 'Yes', 'African American', 155),
 (99, 99, 36.295, 2963, 241, 2, 68, 14, 'Female', 'Yes', 'No', 'African American', 375),
 (100, 100, 83.851, 8494, 607, 5, 47, 18, ' Male', 'No', 'No', 'Caucasian', 1311),
 (101, 101, 21.153, 3736, 256, 1, 41, 11, ' Male', 'No', 'No', 'Caucasian', 298),
 (102, 102, 17.976, 2433, 190, 3, 70, 16, 'Female', 'Yes', 'No', 'Caucasian', 431),
 (103, 103, 68.713, 7582, 531, 2, 56, 16, ' Male', 'Yes', 'No', 'Caucasian', 1587),
 (104, 104, 146.183, 9540, 682, 6, 66, 15, ' Male', 'No', 'No', 'Caucasian', 1050),
 (105, 105, 15.846, 4768, 365, 4, 53, 12, 'Female', 'No', 'No', 'Caucasian', 745),
 (106, 106, 12.031, 3182, 259, 2, 58, 18, 'Female', 'No', 'Yes', 'Caucasian', 210),
 (107, 107, 16.819, 1337, 115, 2, 74, 15, ' Male', 'No', 'Yes', 'Asian', 0),
 (108, 108, 39.11, 3189, 263, 3, 72, 12, ' Male', 'No', 'No', 'Asian', 0),
 (109, 109, 107.986, 6033, 449, 4, 64, 14, ' Male', 'No', 'Yes', 'Caucasian', 227),
 (110, 110, 13.561, 3261, 279, 5, 37, 19, ' Male', 'No', 'Yes', 'Asian', 297),
 (111, 111, 34.537, 3271, 250, 3, 57, 17, 'Female', 'No', 'Yes', 'Asian', 47),
 (112, 112, 28.575, 2959, 231, 2, 60, 11, 'Female', 'No', 'No', 'African American', 0),
 (113, 113, 46.007, 6637, 491, 4, 42, 14, ' Male', 'No', 'Yes', 'Caucasian', 1046),
 (114, 114, 69.251, 6386, 474, 4, 30, 12, 'Female', 'No', 'Yes', 'Asian', 768),
 (115, 115, 16.482, 3326, 268, 4, 41, 15, ' Male', 'No', 'No', 'Caucasian', 271),
 (116, 116, 40.442, 4828, 369, 5, 81, 8, 'Female', 'No', 'No', 'African American', 510),
 (117, 117, 35.177, 2117, 186, 3, 62, 16, 'Female', 'No', 'No', 'Caucasian', 0),
 (118, 118, 91.362, 9113, 626, 1, 47, 17, ' Male', 'No', 'Yes', 'Asian', 1341),
 (119, 119, 27.039, 2161, 173, 3, 40, 17, 'Female', 'No', 'No', 'Caucasian', 0),
 (120, 120, 23.012, 1410, 137, 3, 81, 16, ' Male', 'No', 'No', 'Caucasian', 0),
 (121, 121, 27.241, 1402, 128, 2, 67, 15, 'Female', 'No', 'Yes', 'Asian', 0),
 (122, 122, 148.08, 8157, 599, 2, 83, 13, ' Male', 'No', 'Yes', 'Caucasian', 454),
 (123, 123, 62.602, 7056, 481, 1, 84, 11, 'Female', 'No', 'No', 'Caucasian', 904),
 (124, 124, 11.808, 1300, 117, 3, 77, 14, 'Female', 'No', 'No', 'African American', 0),
 (125, 125, 29.564, 2529, 192, 1, 30, 12, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (126, 126, 27.578, 2531, 195, 1, 34, 15, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (127, 127, 26.427, 5533, 433, 5, 50, 15, 'Female', 'Yes', 'Yes', 'Asian', 1404),
 (128, 128, 57.202, 3411, 259, 3, 72, 11, 'Female', 'No', 'No', 'Caucasian', 0),
 (129, 129, 123.299, 8376, 610, 2, 89, 17, ' Male', 'Yes', 'No', 'African American', 1259),
 (130, 130, 18.145, 3461, 279, 3, 56, 15, ' Male', 'No', 'Yes', 'African American', 255),
 (131, 131, 23.793, 3821, 281, 4, 56, 12, 'Female', 'Yes', 'Yes', 'African American', 868),
 (132, 132, 10.726, 1568, 162, 5, 46, 19, ' Male', 'No', 'Yes', 'Asian', 0),
 (133, 133, 23.283, 5443, 407, 4, 49, 13, ' Male', 'No', 'Yes', 'African American', 912),
 (134, 134, 21.455, 5829, 427, 4, 80, 12, 'Female', 'No', 'Yes', 'African American', 1018),
 (135, 135, 34.664, 5835, 452, 3, 77, 15, 'Female', 'No', 'Yes', 'African American', 835),
 (136, 136, 44.473, 3500, 257, 3, 81, 16, 'Female', 'No', 'No', 'African American', 8),
 (137, 137, 54.663, 4116, 314, 2, 70, 8, 'Female', 'No', 'No', 'African American', 75),
 (138, 138, 36.355, 3613, 278, 4, 35, 9, ' Male', 'No', 'Yes', 'Asian', 187),
 (139, 139, 21.374, 2073, 175, 2, 74, 11, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (140, 140, 107.841, 10384, 728, 3, 87, 7, ' Male', 'No', 'No', 'African American', 1597),
 (141, 141, 39.831, 6045, 459, 3, 32, 12, 'Female', 'Yes', 'Yes', 'African American', 1425),
 (142, 142, 91.876, 6754, 483, 2, 33, 10, ' Male', 'No', 'Yes', 'Caucasian', 605),
 (143, 143, 103.893, 7416, 549, 3, 84, 17, ' Male', 'No', 'No', 'Asian', 669),
 (144, 144, 19.636, 4896, 387, 3, 64, 10, 'Female', 'No', 'No', 'African American', 710),
 (145, 145, 17.392, 2748, 228, 3, 32, 14, ' Male', 'No', 'Yes', 'Caucasian', 68),
 (146, 146, 19.529, 4673, 341, 2, 51, 14, ' Male', 'No', 'No', 'Asian', 642),
 (147, 147, 17.055, 5110, 371, 3, 55, 15, 'Female', 'No', 'Yes', 'Caucasian', 805),
 (148, 148, 23.857, 1501, 150, 3, 56, 16, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (149, 149, 15.184, 2420, 192, 2, 69, 11, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (150, 150, 13.444, 886, 121, 5, 44, 10, ' Male', 'No', 'Yes', 'Asian', 0),
 (151, 151, 63.931, 5728, 435, 3, 28, 14, 'Female', 'No', 'Yes', 'African American', 581),
 (152, 152, 35.864, 4831, 353, 3, 66, 13, 'Female', 'No', 'Yes', 'Caucasian', 534),
 (153, 153, 41.419, 2120, 184, 4, 24, 11, 'Female', 'Yes', 'No', 'Caucasian', 156),
 (154, 154, 92.112, 4612, 344, 3, 32, 17, ' Male', 'No', 'No', 'Caucasian', 0),
 (155, 155, 55.056, 3155, 235, 2, 31, 16, ' Male', 'No', 'Yes', 'African American', 0),
 (156, 156, 19.537, 1362, 143, 4, 34, 9, 'Female', 'No', 'Yes', 'Asian', 0),
 (157, 157, 31.811, 4284, 338, 5, 75, 13, 'Female', 'No', 'Yes', 'Caucasian', 429),
 (158, 158, 56.256, 5521, 406, 2, 72, 16, 'Female', 'Yes', 'Yes', 'Caucasian', 1020),
 (159, 159, 42.357, 5550, 406, 2, 83, 12, 'Female', 'No', 'Yes', 'Asian', 653),
 (160, 160, 53.319, 3000, 235, 3, 53, 13, ' Male', 'No', 'No', 'Asian', 0),
 (161, 161, 12.238, 4865, 381, 5, 67, 11, 'Female', 'No', 'No', 'Caucasian', 836),
 (162, 162, 31.353, 1705, 160, 3, 81, 14, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (163, 163, 63.809, 7530, 515, 1, 56, 12, ' Male', 'No', 'Yes', 'Caucasian', 1086),
 (164, 164, 13.676, 2330, 203, 5, 80, 16, 'Female', 'No', 'No', 'African American', 0),
 (165, 165, 76.782, 5977, 429, 4, 44, 12, ' Male', 'No', 'Yes', 'Asian', 548),
 (166, 166, 25.383, 4527, 367, 4, 46, 11, ' Male', 'No', 'Yes', 'Caucasian', 570),
 (167, 167, 35.691, 2880, 214, 2, 35, 15, ' Male', 'No', 'No', 'African American', 0),
 (168, 168, 29.403, 2327, 178, 1, 37, 14, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (169, 169, 27.47, 2820, 219, 1, 32, 11, 'Female', 'No', 'Yes', 'Asian', 0),
 (170, 170, 27.33, 6179, 459, 4, 36, 12, 'Female', 'No', 'Yes', 'Caucasian', 1099),
 (171, 171, 34.772, 2021, 167, 3, 57, 9, ' Male', 'No', 'No', 'Asian', 0),
 (172, 172, 36.934, 4270, 299, 1, 63, 9, 'Female', 'No', 'Yes', 'Caucasian', 283),
 (173, 173, 76.348, 4697, 344, 4, 60, 18, ' Male', 'No', 'No', 'Asian', 108),
 (174, 174, 14.887, 4745, 339, 3, 58, 12, ' Male', 'No', 'Yes', 'African American', 724),
 (175, 175, 121.834, 10673, 750, 3, 54, 16, ' Male', 'No', 'No', 'African American', 1573),
 (176, 176, 30.132, 2168, 206, 3, 52, 17, ' Male', 'No', 'No', 'Caucasian', 0),
 (177, 177, 24.05, 2607, 221, 4, 32, 18, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (178, 178, 22.379, 3965, 292, 2, 34, 14, 'Female', 'No', 'Yes', 'Asian', 384),
 (179, 179, 28.316, 4391, 316, 2, 29, 10, 'Female', 'No', 'No', 'Caucasian', 453),
 (180, 180, 58.026, 7499, 560, 5, 67, 11, 'Female', 'No', 'No', 'Caucasian', 1237),
 (181, 181, 10.635, 3584, 294, 5, 69, 16, ' Male', 'No', 'Yes', 'Asian', 423),
 (182, 182, 46.102, 5180, 382, 3, 81, 12, ' Male', 'No', 'Yes', 'African American', 516),
 (183, 183, 58.929, 6420, 459, 2, 66, 9, 'Female', 'No', 'Yes', 'African American', 789),
 (184, 184, 80.861, 4090, 335, 3, 29, 15, 'Female', 'No', 'Yes', 'Asian', 0),
 (185, 185, 158.889, 11589, 805, 1, 62, 17, 'Female', 'No', 'Yes', 'Caucasian', 1448),
 (186, 186, 30.42, 4442, 316, 1, 30, 14, 'Female', 'No', 'No', 'African American', 450),
 (187, 187, 36.472, 3806, 309, 2, 52, 13, ' Male', 'No', 'No', 'African American', 188),
 (188, 188, 23.365, 2179, 167, 2, 75, 15, ' Male', 'No', 'No', 'Asian', 0),
 (189, 189, 83.869, 7667, 554, 2, 83, 11, ' Male', 'No', 'No', 'African American', 930),
 (190, 190, 58.351, 4411, 326, 2, 85, 16, 'Female', 'No', 'Yes', 'Caucasian', 126),
 (191, 191, 55.187, 5352, 385, 4, 50, 17, 'Female', 'No', 'Yes', 'Caucasian', 538),
 (192, 192, 124.29, 9560, 701, 3, 52, 17, 'Female', 'Yes', 'No', 'Asian', 1687),
 (193, 193, 28.508, 3933, 287, 4, 56, 14, ' Male', 'No', 'Yes', 'Asian', 336),
 (194, 194, 130.209, 10088, 730, 7, 39, 19, 'Female', 'No', 'Yes', 'Caucasian', 1426),
 (195, 195, 30.406, 2120, 181, 2, 79, 14, ' Male', 'No', 'Yes', 'African American', 0),
 (196, 196, 23.883, 5384, 398, 2, 73, 16, 'Female', 'No', 'Yes', 'African American', 802),
 (197, 197, 93.039, 7398, 517, 1, 67, 12, ' Male', 'No', 'Yes', 'African American', 749),
 (198, 198, 50.699, 3977, 304, 2, 84, 17, 'Female', 'No', 'No', 'African American', 69),
 (199, 199, 27.349, 2000, 169, 4, 51, 16, 'Female', 'No', 'Yes', 'African American', 0),
 (200, 200, 10.403, 4159, 310, 3, 43, 7, ' Male', 'No', 'Yes', 'Asian', 571),
 (201, 201, 23.949, 5343, 383, 2, 40, 18, ' Male', 'No', 'Yes', 'African American', 829),
 (202, 202, 73.914, 7333, 529, 6, 67, 15, 'Female', 'No', 'Yes', 'Caucasian', 1048),
 (203, 203, 21.038, 1448, 145, 2, 58, 13, 'Female', 'No', 'Yes', 'Caucasian', 0),
 (204, 204, 68.206, 6784, 499, 5, 40, 16, 'Female', 'Yes', 'No', 'African American', 1411),
 (205, 205, 57.337, 5310, 392, 2, 45, 7, 'Female', 'No', 'No', 'Caucasian', 456),
 (206, 206, 10.793, 3878, 321, 8, 29, 13, ' Male', 'No', 'No', 'Caucasian', 638),
 (207, 207, 23.45, 2450, 180, 2, 78, 13, ' Male', 'No', 'No', 'Caucasian', 0),
 (208, 208, 10.842, 4391, 358, 5, 37, 10, 'Female', 'Yes', 'Yes', 'Caucasian', 1216),
 (209, 209, 51.345, 4327, 320, 3, 46, 15, ' Male', 'No', 'No', 'African American', 230),
 (210, 210, 151.947, 9156, 642, 2, 91, 11, 'Female', 'No', 'Yes', 'African American', 732),
 (211, 211, 24.543, 3206, 243, 2, 62, 12, 'Female', 'No', 'Yes', 'Caucasian', 95),
 (212, 212, 29.567, 5309, 397, 3, 25, 15, ' Male', 'No', 'No', 'Caucasian', 799),
 (213, 213, 39.145, 4351, 323, 2, 66, 13, ' Male', 'No', 'Yes', 'Caucasian', 308),
 (214, 214, 39.422, 5245, 383, 2, 44, 19, ' Male', 'No', 'No', 'African American', 637),
 (215, 215, 34.909, 5289, 410, 2, 62, 16, 'Female', 'No', 'Yes', 'Caucasian', 681),
 (216, 216, 41.025, 4229, 337, 3, 79, 19, 'Female', 'No', 'Yes', 'Caucasian', 246),
 (217, 217, 15.476, 2762, 215, 3, 60, 18, ' Male', 'No', 'No', 'Asian', 52),
 (218, 218, 12.456, 5395, 392, 3, 65, 14, ' Male', 'No', 'Yes', 'Caucasian', 955),
 (219, 219, 10.627, 1647, 149, 2, 71, 10, 'Female', 'Yes', 'Yes', 'Asian', 195),
 (220, 220, 38.954, 5222, 370, 4, 76, 13, 'Female', 'No', 'No', 'Caucasian', 653),
 (221, 221, 44.847, 5765, 437, 3, 53, 13, 'Female', 'Yes', 'No', 'Asian', 1246),
 (222, 222, 98.515, 8760, 633, 5, 78, 11, 'Female', 'No', 'No', 'African American', 1230),
 (223, 223, 33.437, 6207, 451, 4, 44, 9, ' Male', 'Yes', 'No', 'Caucasian', 1549),
 (224, 224, 27.512, 4613, 344, 5, 72, 17, ' Male', 'No', 'Yes', 'Asian', 573),
 (225, 225, 121.709, 7818, 584, 4, 50, 6, ' Male', 'No', 'Yes', 'Caucasian', 701),
 (226, 226, 15.079, 5673, 411, 4, 28, 15, 'Female', 'No', 'Yes', 'Asian', 1075),
 (227, 227, 59.879, 6906, 527, 6, 78, 15, 'Female', 'No', 'No', 'Caucasian', 1032),
 (228, 228, 66.989, 5614, 430, 3, 47, 14, 'Female', 'No', 'Yes', 'Caucasian', 482),
 (229, 229, 69.165, 4668, 341, 2, 34, 11, 'Female', 'No', 'No', 'African American', 156),
 (230, 230, 69.943, 7555, 547, 3, 76, 9, ' Male', 'No', 'Yes', 'Asian', 1058),
 (231, 231, 33.214, 5137, 387, 3, 59, 9, ' Male', 'No', 'No', 'African American', 661),
 (232, 232, 25.124, 4776, 378, 4, 29, 12, ' Male', 'No', 'Yes', 'Caucasian', 657),
 (233, 233, 15.741, 4788, 360, 1, 39, 14, ' Male', 'No', 'Yes', 'Asian', 689),
 (234, 234, 11.603, 2278, 187, 3, 71, 11, ' Male', 'No', 'Yes', 'Caucasian', 0),
 (235, 235, 69.656, 8244, 579, 3, 41, 14, ' Male', 'No', 'Yes', 'African American', 1329),
 (236, 236, 10.503, 2923, 232, 3, 25, 18, 'Female', 'No', 'Yes', 'African American', 191),
 (237, 237, 42.529, 4986, 369, 2, 37, 11, ' Male', 'No', 'Yes', 'Asian', 489),
 (238, 238, 60.579, 5149, 388, 5, 38, 15, ' Male', 'No', 'Yes', 'Asian', 443),
 (239, 239, 26.532, 2910, 236, 6, 58, 19, 'Female', 'No', 'Yes', 'Caucasian', 52),
 (240, 240, 27.952, 3557, 263, 1, 35, 13, 'Female', 'No', 'Yes', 'Asian', 163),
 (241, 241, 29.705, 3351, 262, 5, 71, 14, 'Female', 'No', 'Yes', 'Asian', 148),